//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaiLy()
        {
            this.DaiLyDebts = new HashSet<DaiLyDebt>();
            this.DaiLyDebtTiens = new HashSet<DaiLyDebtTien>();
            this.DaiLyDebtTiens1 = new HashSet<DaiLyDebtTien>();
            this.XuatSachMasters = new HashSet<XuatSachMaster>();
        }
    
        public int dailyID { get; set; }
        public string daily_ten { get; set; }
        public string daily_diachi { get; set; }
        public string daily_sdt { get; set; }
        public string daily_user { get; set; }
        public string daily_pass { get; set; }
        public Nullable<double> daily_debtmax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiLyDebt> DaiLyDebts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiLyDebtTien> DaiLyDebtTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiLyDebtTien> DaiLyDebtTiens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatSachMaster> XuatSachMasters { get; set; }
    }
}
