//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiLyDebtTien
    {
        public int dailydebttienID { get; set; }
        public Nullable<int> fk_dailyID { get; set; }
        public Nullable<double> dailydebttien_tien { get; set; }
        public Nullable<System.DateTime> dailydebttien_ngaycapnhat { get; set; }
        public Nullable<int> dailydebttien_sach { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual DaiLy DaiLy1 { get; set; }
    }
}
