//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiLyDebt
    {
        public int dailydebtID { get; set; }
        public Nullable<int> fk_dailyID { get; set; }
        public Nullable<int> fk_sachID { get; set; }
        public Nullable<int> dailydebt_soluong { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
