//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int doanhthuID { get; set; }
        public Nullable<double> doanhthu_tien { get; set; }
        public Nullable<System.DateTime> doanhthu_ngaycapnhat { get; set; }
    }
}
