//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapSachMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhapSachMaster()
        {
            this.NhapSachDetails = new HashSet<NhapSachDetail>();
        }
    
        public int nhapsachID { get; set; }
        public Nullable<int> fk_nxbID { get; set; }
        public Nullable<System.DateTime> nhapsach_ngaygiao { get; set; }
        public string nhapsach_nguoigiao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapSachDetail> NhapSachDetails { get; set; }
        public virtual NXB NXB { get; set; }
    }
}
