//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapSachDetail
    {
        public int ctnhapsachID { get; set; }
        public Nullable<int> nhapsachID { get; set; }
        public Nullable<int> fk_sachID { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual NhapSachMaster NhapSachMaster { get; set; }
    }
}
