//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NXBDebt
    {
        public int nxbdebtID { get; set; }
        public Nullable<int> fk_nxbID { get; set; }
        public Nullable<int> fk_sachID { get; set; }
        public Nullable<int> nxbdebt_soluong { get; set; }
        public Nullable<int> nxbdebt_banduoc { get; set; }
    
        public virtual NXB NXB { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
