//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NXBDebtTien
    {
        public int nxbdebttienID { get; set; }
        public Nullable<double> nxbdebttien_tien { get; set; }
        public Nullable<System.DateTime> nxbdebttien_ngaycapnhat { get; set; }
        public Nullable<int> fk_nxbID { get; set; }
    
        public virtual NXB NXB { get; set; }
    }
}
