//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatSachMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XuatSachMaster()
        {
            this.XuatSachDetails = new HashSet<XuatSachDetail>();
        }
    
        public int xuatsachID { get; set; }
        public Nullable<int> fk_dailyID { get; set; }
        public Nullable<System.DateTime> xuatsach_ngayorder { get; set; }
        public Nullable<System.DateTime> xuatsach_ngayupdate { get; set; }
        public string xuatsach_nguoinhan { get; set; }
        public string xuatsach_trangthai { get; set; }
        public Nullable<double> xuatsach_tongtien { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatSachDetail> XuatSachDetails { get; set; }
    }
}
